/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

#include "iceberg/catalog/hive/hms_client.h"

#include <cctype>
#include <charconv>
#include <memory>
#include <string>
#include <string_view>
#include <system_error>
#include <utility>
#include <vector>

#include <thrift/Thrift.h>
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/transport/TBufferTransports.h>
#include <thrift/transport/TSocket.h>
#include <thrift/transport/TTransportException.h>

#include "ThriftHiveMetastore.h"  // generated by C04, located under gen-cpp/
#include "iceberg/catalog/hive/hive_errors.h"
#include "iceberg/util/macros.h"

namespace iceberg::hive {

namespace {

constexpr std::string_view kThriftPrefix = "thrift://";
constexpr int kDefaultHmsPort = 9083;

std::string_view StripScheme(std::string_view spec) {
  if (spec.starts_with(kThriftPrefix)) {
    return spec.substr(kThriftPrefix.size());
  }
  return spec;
}

std::string_view Trim(std::string_view spec) {
  while (!spec.empty() && (std::isspace(static_cast<unsigned char>(spec.front())) != 0)) {
    spec.remove_prefix(1);
  }
  while (!spec.empty() && (std::isspace(static_cast<unsigned char>(spec.back())) != 0)) {
    spec.remove_suffix(1);
  }
  return spec;
}

Result<HmsEndpoint> ParseSingleEndpoint(std::string_view spec) {
  spec = Trim(spec);
  spec = StripScheme(spec);
  spec = Trim(spec);
  if (spec.empty()) {
    return InvalidArgument("Empty HMS endpoint in URI list.");
  }

  HmsEndpoint endpoint;
  const auto colon = spec.rfind(':');
  if (colon == std::string_view::npos) {
    endpoint.host = std::string(spec);
    endpoint.port = kDefaultHmsPort;
    return endpoint;
  }

  endpoint.host = std::string(spec.substr(0, colon));
  if (endpoint.host.empty()) {
    return InvalidArgument("HMS endpoint has empty host: '{}'.", spec);
  }

  const auto port_str = spec.substr(colon + 1);
  if (port_str.empty()) {
    endpoint.port = kDefaultHmsPort;
    return endpoint;
  }

  int port = 0;
  const auto [_, ec] =
      std::from_chars(port_str.data(), port_str.data() + port_str.size(), port);
  if (ec != std::errc() || port <= 0 || port > 65535) {
    return InvalidArgument("Invalid HMS port in endpoint '{}'.", spec);
  }
  endpoint.port = port;
  return endpoint;
}

}  // namespace

Result<std::vector<HmsEndpoint>> ParseHmsUris(std::string_view uri) {
  std::vector<HmsEndpoint> endpoints;
  if (Trim(uri).empty()) {
    return InvalidArgument("HMS URI is empty.");
  }

  std::size_t pos = 0;
  while (pos <= uri.size()) {
    const auto comma = uri.find(',', pos);
    const auto piece = uri.substr(
        pos, comma == std::string_view::npos ? std::string_view::npos : comma - pos);
    ICEBERG_ASSIGN_OR_RAISE(auto endpoint, ParseSingleEndpoint(piece));
    endpoints.push_back(std::move(endpoint));
    if (comma == std::string_view::npos) {
      break;
    }
    pos = comma + 1;
  }
  return endpoints;
}

// ---------------------------------------------------------------------------
// HmsClient::Impl owns the Thrift state. The destruction order matters:
// the generated client borrows the protocol, the protocol borrows the
// transport, the transport borrows the socket. With std::shared_ptr
// fields the runtime handles refcounting, but we still hold them in the
// declared order so that the client tears down first.

class HmsClient::Impl {
 public:
  std::shared_ptr<apache::thrift::transport::TSocket> socket;
  std::shared_ptr<apache::thrift::transport::TTransport> transport;
  std::shared_ptr<apache::thrift::protocol::TProtocol> protocol;
  std::unique_ptr<Apache::Hadoop::Hive::ThriftHiveMetastoreClient> client;
};

namespace {

using Apache::Hadoop::Hive::AlreadyExistsException;
using Apache::Hadoop::Hive::Database;
using Apache::Hadoop::Hive::FieldSchema;
using Apache::Hadoop::Hive::GetTableRequest;
using Apache::Hadoop::Hive::GetTableResult;
using Apache::Hadoop::Hive::InvalidObjectException;
using Apache::Hadoop::Hive::InvalidOperationException;
using Apache::Hadoop::Hive::LockComponent;
using Apache::Hadoop::Hive::LockLevel;
using Apache::Hadoop::Hive::LockRequest;
using Apache::Hadoop::Hive::LockResponse;
using Apache::Hadoop::Hive::LockState;
using Apache::Hadoop::Hive::LockType;
using Apache::Hadoop::Hive::MetaException;
using Apache::Hadoop::Hive::NoSuchLockException;
using Apache::Hadoop::Hive::NoSuchObjectException;
using Apache::Hadoop::Hive::PrincipalType;
using Apache::Hadoop::Hive::SerDeInfo;
using Apache::Hadoop::Hive::StorageDescriptor;
using Apache::Hadoop::Hive::Table;
using Apache::Hadoop::Hive::TxnAbortedException;
using Apache::Hadoop::Hive::TxnOpenException;
using Apache::Hadoop::Hive::UnknownDBException;
using Apache::Hadoop::Hive::UnknownTableException;
using Apache::Hadoop::Hive::UnlockRequest;

Database ToThriftDatabase(const HiveDatabase& database) {
  Database thrift_db;
  thrift_db.__set_name(database.name);
  if (!database.description.empty()) {
    thrift_db.__set_description(database.description);
  }
  if (!database.location_uri.empty()) {
    thrift_db.__set_locationUri(database.location_uri);
  }
  if (!database.parameters.empty()) {
    thrift_db.__set_parameters(std::map<std::string, std::string>(
        database.parameters.begin(), database.parameters.end()));
  }
  if (!database.owner_name.empty()) {
    thrift_db.__set_ownerName(database.owner_name);
  }
  if (database.owner_type == "ROLE") {
    thrift_db.__set_ownerType(PrincipalType::ROLE);
  } else if (database.owner_type == "USER") {
    thrift_db.__set_ownerType(PrincipalType::USER);
  } else if (database.owner_type == "GROUP") {
    thrift_db.__set_ownerType(PrincipalType::GROUP);
  }
  return thrift_db;
}

Table ToThriftTable(const HiveTable& table) {
  Table thrift_table;
  thrift_table.__set_dbName(table.db_name);
  thrift_table.__set_tableName(table.table_name);
  if (!table.owner.empty()) {
    thrift_table.__set_owner(table.owner);
  }
  if (!table.table_type.empty()) {
    thrift_table.__set_tableType(table.table_type);
  }
  if (!table.parameters.empty()) {
    thrift_table.__set_parameters(std::map<std::string, std::string>(
        table.parameters.begin(), table.parameters.end()));
  }

  StorageDescriptor sd;
  sd.__set_location(table.location);
  if (!table.input_format.empty()) {
    sd.__set_inputFormat(table.input_format);
  }
  if (!table.output_format.empty()) {
    sd.__set_outputFormat(table.output_format);
  }

  std::vector<FieldSchema> cols;
  cols.reserve(table.columns.size());
  for (const auto& column : table.columns) {
    FieldSchema field;
    field.__set_name(column.name);
    field.__set_type(column.type_string);
    if (!column.comment.empty()) {
      field.__set_comment(column.comment);
    }
    cols.push_back(std::move(field));
  }
  sd.__set_cols(std::move(cols));

  SerDeInfo serde;
  if (!table.serde.empty()) {
    serde.__set_serializationLib(table.serde);
  }
  sd.__set_serdeInfo(std::move(serde));

  thrift_table.__set_sd(std::move(sd));
  return thrift_table;
}

HiveTable FromThriftTable(const Table& thrift_table) {
  HiveTable table;
  table.db_name = thrift_table.dbName;
  table.table_name = thrift_table.tableName;
  table.owner = thrift_table.owner;
  table.table_type = thrift_table.tableType;
  table.location = thrift_table.sd.location;
  table.input_format = thrift_table.sd.inputFormat;
  table.output_format = thrift_table.sd.outputFormat;
  table.serde = thrift_table.sd.serdeInfo.serializationLib;
  table.parameters.insert(thrift_table.parameters.begin(), thrift_table.parameters.end());

  table.columns.reserve(thrift_table.sd.cols.size());
  for (const auto& column : thrift_table.sd.cols) {
    table.columns.push_back(HiveColumn{
        .name = column.name, .type_string = column.type, .comment = column.comment});
  }
  return table;
}

HiveDatabase FromThriftDatabase(const Database& thrift_db) {
  HiveDatabase database;
  database.name = thrift_db.name;
  database.description = thrift_db.description;
  database.location_uri = thrift_db.locationUri;
  database.parameters.insert(thrift_db.parameters.begin(), thrift_db.parameters.end());
  database.owner_name = thrift_db.ownerName;
  switch (thrift_db.ownerType) {
    case PrincipalType::USER:
      database.owner_type = "USER";
      break;
    case PrincipalType::ROLE:
      database.owner_type = "ROLE";
      break;
    case PrincipalType::GROUP:
      database.owner_type = "GROUP";
      break;
  }
  return database;
}

}  // namespace

HmsClient::HmsClient(std::unique_ptr<Impl> impl) : impl_(std::move(impl)) {}

HmsClient::~HmsClient() {
  if (impl_ && impl_->transport && impl_->transport->isOpen()) {
    try {
      impl_->transport->close();
    } catch (const apache::thrift::TException&) {
      // Best-effort close on teardown; ignore exceptions.
    }
  }
}

Result<std::unique_ptr<HmsClient>> HmsClient::Connect(
    const HiveCatalogProperties& config) {
  ICEBERG_ASSIGN_OR_RAISE(auto uri, config.Uri());
  ICEBERG_ASSIGN_OR_RAISE(auto endpoints, ParseHmsUris(uri));
  ICEBERG_ASSIGN_OR_RAISE(auto transport_mode, config.ThriftTransport());

  // HA failover beyond the first endpoint is left for a later commit.
  const HmsEndpoint& endpoint = endpoints.front();
  const int connect_timeout_ms = config.Get(HiveCatalogProperties::kConnectTimeoutMs);
  const int socket_timeout_ms = config.Get(HiveCatalogProperties::kSocketTimeoutMs);

  auto socket =
      std::make_shared<apache::thrift::transport::TSocket>(endpoint.host, endpoint.port);
  socket->setConnTimeout(connect_timeout_ms);
  socket->setRecvTimeout(socket_timeout_ms);
  socket->setSendTimeout(socket_timeout_ms);

  std::shared_ptr<apache::thrift::transport::TTransport> transport;
  switch (transport_mode) {
    case HiveThriftTransport::kBuffered:
      transport = std::make_shared<apache::thrift::transport::TBufferedTransport>(socket);
      break;
    case HiveThriftTransport::kFramed:
      transport = std::make_shared<apache::thrift::transport::TFramedTransport>(socket);
      break;
  }

  auto protocol = std::make_shared<apache::thrift::protocol::TBinaryProtocol>(transport);
  auto client =
      std::make_unique<Apache::Hadoop::Hive::ThriftHiveMetastoreClient>(protocol);

  try {
    transport->open();
  } catch (const apache::thrift::transport::TTransportException& e) {
    return IOError("Failed to connect to HMS at {}:{} : {}", endpoint.host, endpoint.port,
                   e.what());
  } catch (const apache::thrift::TException& e) {
    return IOError("Thrift error contacting HMS at {}:{} : {}", endpoint.host,
                   endpoint.port, e.what());
  }

  auto impl = std::make_unique<HmsClient::Impl>();
  impl->socket = std::move(socket);
  impl->transport = std::move(transport);
  impl->protocol = std::move(protocol);
  impl->client = std::move(client);
  return std::unique_ptr<HmsClient>(new HmsClient(std::move(impl)));
}

// ---------------------------------------------------------------------------
// Database (namespace) operations. Each method follows the same shape:
//   * call the generated Thrift method,
//   * convert the result to / from HiveDatabase,
//   * catch the specific HMS exception subclasses and dispatch through
//     hive_errors so callers see typed iceberg::Error values.

Result<std::vector<std::string>> HmsClient::GetAllDatabases() {
  std::vector<std::string> names;
  try {
    impl_->client->get_all_databases(names);
    return names;
  } catch (const MetaException& e) {
    return MetaError("get_all_databases", e.message);
  } catch (const apache::thrift::TException& e) {
    return GenericThriftError("get_all_databases", e.what());
  }
}

Result<HiveDatabase> HmsClient::GetDatabase(std::string_view name) {
  Database thrift_db;
  try {
    impl_->client->get_database(thrift_db, std::string(name));
    return FromThriftDatabase(thrift_db);
  } catch (const NoSuchObjectException& e) {
    return UnknownDBError("get_database", e.message);
  } catch (const UnknownDBException& e) {
    return UnknownDBError("get_database", e.message);
  } catch (const MetaException& e) {
    return MetaError("get_database", e.message);
  } catch (const apache::thrift::TException& e) {
    return GenericThriftError("get_database", e.what());
  }
}

Status HmsClient::CreateDatabase(const HiveDatabase& database) {
  const Database thrift_db = ToThriftDatabase(database);
  try {
    impl_->client->create_database(thrift_db);
    return {};
  } catch (const AlreadyExistsException& e) {
    return AlreadyExistsError("create_database", e.message);
  } catch (const InvalidObjectException& e) {
    return InvalidObjectError("create_database", e.message);
  } catch (const MetaException& e) {
    return MetaError("create_database", e.message);
  } catch (const apache::thrift::TException& e) {
    return GenericThriftError("create_database", e.what());
  }
}

Status HmsClient::DropDatabase(std::string_view name, bool cascade) {
  try {
    impl_->client->drop_database(std::string(name), /*deleteData=*/false, cascade);
    return {};
  } catch (const NoSuchObjectException& e) {
    return UnknownDBError("drop_database", e.message);
  } catch (const InvalidOperationException& e) {
    return InvalidOperationError("drop_database", e.message);
  } catch (const MetaException& e) {
    return MetaError("drop_database", e.message);
  } catch (const apache::thrift::TException& e) {
    return GenericThriftError("drop_database", e.what());
  }
}

Status HmsClient::AlterDatabase(std::string_view name, const HiveDatabase& database) {
  const Database thrift_db = ToThriftDatabase(database);
  try {
    impl_->client->alter_database(std::string(name), thrift_db);
    return {};
  } catch (const NoSuchObjectException& e) {
    return UnknownDBError("alter_database", e.message);
  } catch (const InvalidOperationException& e) {
    return InvalidOperationError("alter_database", e.message);
  } catch (const MetaException& e) {
    return MetaError("alter_database", e.message);
  } catch (const apache::thrift::TException& e) {
    return GenericThriftError("alter_database", e.what());
  }
}

// ---------------------------------------------------------------------------
// Table operations. Same pattern as the database wrappers above.

Result<std::vector<std::string>> HmsClient::GetAllTables(std::string_view db_name) {
  std::vector<std::string> names;
  try {
    impl_->client->get_all_tables(names, std::string(db_name));
    return names;
  } catch (const NoSuchObjectException& e) {
    return UnknownDBError("get_all_tables", e.message);
  } catch (const UnknownDBException& e) {
    return UnknownDBError("get_all_tables", e.message);
  } catch (const MetaException& e) {
    return MetaError("get_all_tables", e.message);
  } catch (const apache::thrift::TException& e) {
    return GenericThriftError("get_all_tables", e.what());
  }
}

Result<HiveTable> HmsClient::GetTable(std::string_view db_name,
                                      std::string_view table_name) {
  GetTableRequest request;
  request.__set_dbName(std::string(db_name));
  request.__set_tblName(std::string(table_name));
  GetTableResult result;
  try {
    impl_->client->get_table_req(result, request);
    return FromThriftTable(result.table);
  } catch (const NoSuchObjectException& e) {
    return UnknownTableError("get_table", e.message);
  } catch (const UnknownTableException& e) {
    return UnknownTableError("get_table", e.message);
  } catch (const UnknownDBException& e) {
    return UnknownDBError("get_table", e.message);
  } catch (const MetaException& e) {
    return MetaError("get_table", e.message);
  } catch (const apache::thrift::TException& e) {
    return GenericThriftError("get_table", e.what());
  }
}

Status HmsClient::CreateTable(const HiveTable& table) {
  const Table thrift_table = ToThriftTable(table);
  try {
    impl_->client->create_table(thrift_table);
    return {};
  } catch (const AlreadyExistsException& e) {
    return AlreadyExistsError("create_table", e.message);
  } catch (const InvalidObjectException& e) {
    return InvalidObjectError("create_table", e.message);
  } catch (const NoSuchObjectException& e) {
    return UnknownDBError("create_table", e.message);
  } catch (const MetaException& e) {
    return MetaError("create_table", e.message);
  } catch (const apache::thrift::TException& e) {
    return GenericThriftError("create_table", e.what());
  }
}

Status HmsClient::DropTable(std::string_view db_name, std::string_view table_name,
                            bool delete_data) {
  try {
    impl_->client->drop_table(std::string(db_name), std::string(table_name), delete_data);
    return {};
  } catch (const NoSuchObjectException& e) {
    return UnknownTableError("drop_table", e.message);
  } catch (const InvalidOperationException& e) {
    return InvalidOperationError("drop_table", e.message);
  } catch (const MetaException& e) {
    return MetaError("drop_table", e.message);
  } catch (const apache::thrift::TException& e) {
    return GenericThriftError("drop_table", e.what());
  }
}

Status HmsClient::AlterTable(std::string_view db_name, std::string_view table_name,
                             const HiveTable& new_table) {
  const Table thrift_table = ToThriftTable(new_table);
  try {
    impl_->client->alter_table(std::string(db_name), std::string(table_name),
                               thrift_table);
    return {};
  } catch (const NoSuchObjectException& e) {
    return UnknownTableError("alter_table", e.message);
  } catch (const InvalidObjectException& e) {
    return InvalidObjectError("alter_table", e.message);
  } catch (const InvalidOperationException& e) {
    return InvalidOperationError("alter_table", e.message);
  } catch (const MetaException& e) {
    return MetaError("alter_table", e.message);
  } catch (const apache::thrift::TException& e) {
    return GenericThriftError("alter_table", e.what());
  }
}

// ---------------------------------------------------------------------------
// HMS locks. Used only when the catalog is configured with
// `hive.lock-enabled=true`. Failure to acquire the lock surfaces as
// kCommitFailed so iceberg::Transaction's retry loop can roll forward.

Result<HmsClient::HmsLockHandle> HmsClient::LockExclusive(std::string_view db_name,
                                                          std::string_view table_name) {
  LockComponent component;
  component.__set_type(LockType::EXCLUSIVE);
  component.__set_level(LockLevel::TABLE);
  component.__set_dbname(std::string(db_name));
  component.__set_tablename(std::string(table_name));
  component.__set_isTransactional(false);
  component.__set_isDynamicPartitionWrite(false);

  LockRequest request;
  request.__set_component({component});
  // No transaction context; iceberg_hive uses HMS locks purely as an
  // advisory mutex around metadata_location CAS.
  request.__set_txnid(0);

  LockResponse response;
  try {
    impl_->client->lock(response, request);
  } catch (const TxnAbortedException& e) {
    return CommitFailed("HMS aborted lock txn on {}.{}: {}", db_name, table_name,
                        e.message);
  } catch (const MetaException& e) {
    return MetaError("lock", e.message);
  } catch (const apache::thrift::TException& e) {
    return GenericThriftError("lock", e.what());
  }

  if (response.state != LockState::ACQUIRED) {
    // HMS still assigns a valid `lockid` for non-ACQUIRED responses
    // (WAITING / NOT_ACQUIRED / ABORT) and the request stays queued on
    // the server until it times out (typically 10 minutes). Release it
    // explicitly so we don't block subsequent EXCLUSIVE requests on the
    // same table for the entire HMS lease window.
    (void)Unlock(HmsLockHandle{.lock_id = response.lockid});
    return CommitFailed(
        "HMS denied EXCLUSIVE lock on {}.{} (state={}, error={}); retry the "
        "transaction.",
        db_name, table_name, static_cast<int>(response.state), response.errorMessage);
  }
  return HmsLockHandle{.lock_id = response.lockid};
}

Status HmsClient::Unlock(HmsLockHandle handle) {
  if (!handle.acquired()) {
    return {};
  }
  UnlockRequest request;
  request.__set_lockid(handle.lock_id);
  try {
    impl_->client->unlock(request);
    return {};
  } catch (const NoSuchLockException& e) {
    return NotFound("HMS reports lock {} no longer exists: {}", handle.lock_id,
                    e.message);
  } catch (const TxnOpenException& e) {
    return InvalidOperationError("unlock", e.message);
  } catch (const MetaException& e) {
    return MetaError("unlock", e.message);
  } catch (const apache::thrift::TException& e) {
    return GenericThriftError("unlock", e.what());
  }
}

}  // namespace iceberg::hive
