/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

#include "iceberg/catalog/hive/hms_client.h"

#include <algorithm>
#include <cctype>
#include <charconv>
#include <chrono>
#include <condition_variable>
#include <format>
#include <memory>
#include <mutex>
#include <string>
#include <string_view>
#include <system_error>
#include <thread>
#include <utility>
#include <vector>

#include <thrift/Thrift.h>
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/transport/TBufferTransports.h>
#include <thrift/transport/TSocket.h>
#include <thrift/transport/TTransportException.h>

#include "ThriftHiveMetastore.h"  // generated by C04, located under gen-cpp/
#include "iceberg/catalog/hive/hive_errors.h"
#include "iceberg/util/macros.h"

namespace iceberg::hive {

namespace {

constexpr std::string_view kThriftPrefix = "thrift://";
constexpr int kDefaultHmsPort = 9083;

std::string_view StripScheme(std::string_view spec) {
  if (spec.starts_with(kThriftPrefix)) {
    return spec.substr(kThriftPrefix.size());
  }
  return spec;
}

std::string_view Trim(std::string_view spec) {
  while (!spec.empty() && (std::isspace(static_cast<unsigned char>(spec.front())) != 0)) {
    spec.remove_prefix(1);
  }
  while (!spec.empty() && (std::isspace(static_cast<unsigned char>(spec.back())) != 0)) {
    spec.remove_suffix(1);
  }
  return spec;
}

Result<HmsEndpoint> ParseSingleEndpoint(std::string_view spec) {
  spec = Trim(spec);
  spec = StripScheme(spec);
  spec = Trim(spec);
  if (spec.empty()) {
    return InvalidArgument("Empty HMS endpoint in URI list.");
  }

  HmsEndpoint endpoint;
  std::string_view host_part;
  std::string_view port_part;

  // RFC 3986-style bracketed host (`[ipv6]:port`) avoids ambiguity with
  // the colons inside an IPv6 address. Any other input that still
  // contains a colon other than as the host/port separator (e.g., a
  // bare unbracketed IPv6 address) is rejected because we cannot tell
  // host from port reliably.
  if (!spec.empty() && spec.front() == '[') {
    const auto close = spec.find(']');
    if (close == std::string_view::npos || close == 1) {
      return InvalidArgument("HMS endpoint has malformed bracketed host: '{}'.", spec);
    }
    host_part = spec.substr(1, close - 1);
    auto rest = spec.substr(close + 1);
    if (rest.empty()) {
      port_part = {};
    } else if (rest.front() == ':') {
      port_part = rest.substr(1);
    } else {
      return InvalidArgument("HMS endpoint has trailing characters after ']': '{}'.",
                             spec);
    }
  } else {
    const auto colon = spec.find(':');
    if (colon == std::string_view::npos) {
      host_part = spec;
    } else {
      // Reject ambiguous bare IPv6 (multiple colons without brackets).
      if (spec.find(':', colon + 1) != std::string_view::npos) {
        return InvalidArgument(
            "HMS endpoint has multiple ':' separators (bracket IPv6 hosts as "
            "[host]:port): '{}'.",
            spec);
      }
      host_part = spec.substr(0, colon);
      port_part = spec.substr(colon + 1);
    }
  }

  if (host_part.empty()) {
    return InvalidArgument("HMS endpoint has empty host: '{}'.", spec);
  }
  endpoint.host = std::string(host_part);

  if (port_part.empty()) {
    endpoint.port = kDefaultHmsPort;
    return endpoint;
  }

  int port = 0;
  const auto* port_end = port_part.data() + port_part.size();
  const auto [ptr, ec] = std::from_chars(port_part.data(), port_end, port);
  // `from_chars` stops at the first non-digit and reports success as long
  // as one digit was consumed; check ptr to reject trailing garbage like
  // "8080foo" or "]" / ":1]" residue from a malformed IPv6 attempt.
  if (ec != std::errc() || ptr != port_end || port <= 0 || port > 65535) {
    return InvalidArgument("Invalid HMS port in endpoint '{}'.", spec);
  }
  endpoint.port = port;
  return endpoint;
}

}  // namespace

Result<std::vector<HmsEndpoint>> ParseHmsUris(std::string_view uri) {
  std::vector<HmsEndpoint> endpoints;
  if (Trim(uri).empty()) {
    return InvalidArgument("HMS URI is empty.");
  }

  std::size_t pos = 0;
  while (pos <= uri.size()) {
    const auto comma = uri.find(',', pos);
    const auto piece = uri.substr(
        pos, comma == std::string_view::npos ? std::string_view::npos : comma - pos);
    ICEBERG_ASSIGN_OR_RAISE(auto endpoint, ParseSingleEndpoint(piece));
    endpoints.push_back(std::move(endpoint));
    if (comma == std::string_view::npos) {
      break;
    }
    pos = comma + 1;
  }
  return endpoints;
}

// ---------------------------------------------------------------------------
// HmsClient::Impl owns the Thrift state. The destruction order matters:
// the generated client borrows the protocol, the protocol borrows the
// transport, the transport borrows the socket. With std::shared_ptr
// fields the runtime handles refcounting, but we still hold them in the
// declared order so that the client tears down first.

class HmsClient::Impl {
 public:
  std::shared_ptr<apache::thrift::transport::TSocket> socket;
  std::shared_ptr<apache::thrift::transport::TTransport> transport;
  std::shared_ptr<apache::thrift::protocol::TProtocol> protocol;
  std::unique_ptr<Apache::Hadoop::Hive::ThriftHiveMetastoreClient> client;
};

namespace {

using Apache::Hadoop::Hive::AlreadyExistsException;
using Apache::Hadoop::Hive::Database;
using Apache::Hadoop::Hive::FieldSchema;
using Apache::Hadoop::Hive::GetTableRequest;
using Apache::Hadoop::Hive::GetTableResult;
using Apache::Hadoop::Hive::HeartbeatRequest;
using Apache::Hadoop::Hive::InvalidObjectException;
using Apache::Hadoop::Hive::InvalidOperationException;
using Apache::Hadoop::Hive::LockComponent;
using Apache::Hadoop::Hive::LockLevel;
using Apache::Hadoop::Hive::LockRequest;
using Apache::Hadoop::Hive::LockResponse;
using Apache::Hadoop::Hive::LockState;
using Apache::Hadoop::Hive::LockType;
using Apache::Hadoop::Hive::MetaException;
using Apache::Hadoop::Hive::NoSuchLockException;
using Apache::Hadoop::Hive::NoSuchObjectException;
using Apache::Hadoop::Hive::PrincipalType;
using Apache::Hadoop::Hive::SerDeInfo;
using Apache::Hadoop::Hive::StorageDescriptor;
using Apache::Hadoop::Hive::Table;
using Apache::Hadoop::Hive::TxnAbortedException;
using Apache::Hadoop::Hive::TxnOpenException;
using Apache::Hadoop::Hive::UnknownDBException;
using Apache::Hadoop::Hive::UnknownTableException;
using Apache::Hadoop::Hive::UnlockRequest;

Database ToThriftDatabase(const HiveDatabase& database) {
  Database thrift_db;
  thrift_db.__set_name(database.name);
  if (!database.description.empty()) {
    thrift_db.__set_description(database.description);
  }
  if (!database.location_uri.empty()) {
    thrift_db.__set_locationUri(database.location_uri);
  }
  if (!database.parameters.empty()) {
    thrift_db.__set_parameters(std::map<std::string, std::string>(
        database.parameters.begin(), database.parameters.end()));
  }
  if (!database.owner_name.empty()) {
    thrift_db.__set_ownerName(database.owner_name);
  }
  if (database.owner_type == "ROLE") {
    thrift_db.__set_ownerType(PrincipalType::ROLE);
  } else if (database.owner_type == "USER") {
    thrift_db.__set_ownerType(PrincipalType::USER);
  } else if (database.owner_type == "GROUP") {
    thrift_db.__set_ownerType(PrincipalType::GROUP);
  }
  return thrift_db;
}

Table ToThriftTable(const HiveTable& table) {
  Table thrift_table;
  thrift_table.__set_dbName(table.db_name);
  thrift_table.__set_tableName(table.table_name);
  if (!table.owner.empty()) {
    thrift_table.__set_owner(table.owner);
  }
  if (!table.table_type.empty()) {
    thrift_table.__set_tableType(table.table_type);
  }
  if (!table.parameters.empty()) {
    thrift_table.__set_parameters(std::map<std::string, std::string>(
        table.parameters.begin(), table.parameters.end()));
  }

  StorageDescriptor sd;
  sd.__set_location(table.location);
  if (!table.input_format.empty()) {
    sd.__set_inputFormat(table.input_format);
  }
  if (!table.output_format.empty()) {
    sd.__set_outputFormat(table.output_format);
  }

  std::vector<FieldSchema> cols;
  cols.reserve(table.columns.size());
  for (const auto& column : table.columns) {
    FieldSchema field;
    field.__set_name(column.name);
    field.__set_type(column.type_string);
    if (!column.comment.empty()) {
      field.__set_comment(column.comment);
    }
    cols.push_back(std::move(field));
  }
  sd.__set_cols(std::move(cols));

  SerDeInfo serde;
  if (!table.serde.empty()) {
    serde.__set_serializationLib(table.serde);
  }
  sd.__set_serdeInfo(std::move(serde));

  thrift_table.__set_sd(std::move(sd));
  return thrift_table;
}

HiveTable FromThriftTable(const Table& thrift_table) {
  HiveTable table;
  table.db_name = thrift_table.dbName;
  table.table_name = thrift_table.tableName;
  table.owner = thrift_table.owner;
  table.table_type = thrift_table.tableType;
  table.location = thrift_table.sd.location;
  table.input_format = thrift_table.sd.inputFormat;
  table.output_format = thrift_table.sd.outputFormat;
  table.serde = thrift_table.sd.serdeInfo.serializationLib;
  table.parameters.insert(thrift_table.parameters.begin(), thrift_table.parameters.end());

  table.columns.reserve(thrift_table.sd.cols.size());
  for (const auto& column : thrift_table.sd.cols) {
    table.columns.push_back(HiveColumn{
        .name = column.name, .type_string = column.type, .comment = column.comment});
  }
  return table;
}

HiveDatabase FromThriftDatabase(const Database& thrift_db) {
  HiveDatabase database;
  database.name = thrift_db.name;
  database.description = thrift_db.description;
  database.location_uri = thrift_db.locationUri;
  database.parameters.insert(thrift_db.parameters.begin(), thrift_db.parameters.end());
  database.owner_name = thrift_db.ownerName;
  switch (thrift_db.ownerType) {
    case PrincipalType::USER:
      database.owner_type = "USER";
      break;
    case PrincipalType::ROLE:
      database.owner_type = "ROLE";
      break;
    case PrincipalType::GROUP:
      database.owner_type = "GROUP";
      break;
  }
  return database;
}

}  // namespace

HmsClient::HmsClient(std::unique_ptr<Impl> impl) : impl_(std::move(impl)) {}

HmsClient::~HmsClient() {
  if (impl_ && impl_->transport && impl_->transport->isOpen()) {
    try {
      impl_->transport->close();
    } catch (const apache::thrift::TException&) {
      // Best-effort close on teardown; ignore exceptions.
    }
  }
}

Result<std::unique_ptr<HmsClient>> HmsClient::Connect(
    const HiveCatalogProperties& config) {
  ICEBERG_ASSIGN_OR_RAISE(auto uri, config.Uri());
  ICEBERG_ASSIGN_OR_RAISE(auto endpoints, ParseHmsUris(uri));
  ICEBERG_ASSIGN_OR_RAISE(auto transport_mode, config.ThriftTransport());

  const int connect_timeout_ms = config.Get(HiveCatalogProperties::kConnectTimeoutMs);
  const int socket_timeout_ms = config.Get(HiveCatalogProperties::kSocketTimeoutMs);

  // HA failover: try every endpoint parsed from a comma-separated URI
  // list in order. The first one whose `transport->open()` succeeds
  // wins. If every endpoint fails, surface the LAST error (with the
  // attempt count baked into the message) so the operator can tell
  // both how many endpoints we tried and which one died last. Mirrors
  // Java HiveMetaStoreClient's `metastoreUris` failover.
  std::string last_error;
  for (const HmsEndpoint& endpoint : endpoints) {
    auto socket = std::make_shared<apache::thrift::transport::TSocket>(endpoint.host,
                                                                       endpoint.port);
    socket->setConnTimeout(connect_timeout_ms);
    socket->setRecvTimeout(socket_timeout_ms);
    socket->setSendTimeout(socket_timeout_ms);

    std::shared_ptr<apache::thrift::transport::TTransport> transport;
    switch (transport_mode) {
      case HiveThriftTransport::kBuffered:
        transport =
            std::make_shared<apache::thrift::transport::TBufferedTransport>(socket);
        break;
      case HiveThriftTransport::kFramed:
        transport = std::make_shared<apache::thrift::transport::TFramedTransport>(socket);
        break;
    }

    auto protocol =
        std::make_shared<apache::thrift::protocol::TBinaryProtocol>(transport);
    auto client =
        std::make_unique<Apache::Hadoop::Hive::ThriftHiveMetastoreClient>(protocol);

    try {
      transport->open();
    } catch (const apache::thrift::transport::TTransportException& e) {
      last_error = std::format("{}:{} ({})", endpoint.host, endpoint.port, e.what());
      continue;
    } catch (const apache::thrift::TException& e) {
      last_error =
          std::format("{}:{} (thrift error: {})", endpoint.host, endpoint.port, e.what());
      continue;
    }

    auto impl = std::make_unique<HmsClient::Impl>();
    impl->socket = std::move(socket);
    impl->transport = std::move(transport);
    impl->protocol = std::move(protocol);
    impl->client = std::move(client);
    return std::unique_ptr<HmsClient>(new HmsClient(std::move(impl)));
  }
  return IOError("Failed to connect to any of {} HMS endpoint(s); last error: {}",
                 endpoints.size(), last_error);
}

// ---------------------------------------------------------------------------
// Database (namespace) operations. Each method follows the same shape:
//   * call the generated Thrift method,
//   * convert the result to / from HiveDatabase,
//   * catch the specific HMS exception subclasses and dispatch through
//     hive_errors so callers see typed iceberg::Error values.

Result<std::vector<std::string>> HmsClient::GetAllDatabases() {
  std::vector<std::string> names;
  try {
    impl_->client->get_all_databases(names);
    return names;
  } catch (const MetaException& e) {
    return MetaError("get_all_databases", e.message);
  } catch (const apache::thrift::transport::TTransportException& e) {
    return TransportError("get_all_databases", e.what());

  } catch (const apache::thrift::TException& e) {
    return GenericThriftError("get_all_databases", e.what());
  }
}

Result<HiveDatabase> HmsClient::GetDatabase(std::string_view name) {
  Database thrift_db;
  try {
    impl_->client->get_database(thrift_db, std::string(name));
    return FromThriftDatabase(thrift_db);
  } catch (const NoSuchObjectException& e) {
    return UnknownDBError("get_database", e.message);
  } catch (const UnknownDBException& e) {
    return UnknownDBError("get_database", e.message);
  } catch (const MetaException& e) {
    return MetaError("get_database", e.message);
  } catch (const apache::thrift::transport::TTransportException& e) {
    return TransportError("get_database", e.what());

  } catch (const apache::thrift::TException& e) {
    return GenericThriftError("get_database", e.what());
  }
}

Status HmsClient::CreateDatabase(const HiveDatabase& database) {
  const Database thrift_db = ToThriftDatabase(database);
  try {
    impl_->client->create_database(thrift_db);
    return {};
  } catch (const AlreadyExistsException& e) {
    return AlreadyExistsError("create_database", e.message);
  } catch (const InvalidObjectException& e) {
    return InvalidObjectError("create_database", e.message);
  } catch (const MetaException& e) {
    return MetaError("create_database", e.message);
  } catch (const apache::thrift::transport::TTransportException& e) {
    return TransportError("create_database", e.what());

  } catch (const apache::thrift::TException& e) {
    return GenericThriftError("create_database", e.what());
  }
}

Status HmsClient::DropDatabase(std::string_view name, bool cascade) {
  try {
    impl_->client->drop_database(std::string(name), /*deleteData=*/false, cascade);
    return {};
  } catch (const NoSuchObjectException& e) {
    return UnknownDBError("drop_database", e.message);
  } catch (const InvalidOperationException& e) {
    return InvalidOperationError("drop_database", e.message);
  } catch (const MetaException& e) {
    return MetaError("drop_database", e.message);
  } catch (const apache::thrift::transport::TTransportException& e) {
    return TransportError("drop_database", e.what());

  } catch (const apache::thrift::TException& e) {
    return GenericThriftError("drop_database", e.what());
  }
}

Status HmsClient::AlterDatabase(std::string_view name, const HiveDatabase& database) {
  const Database thrift_db = ToThriftDatabase(database);
  try {
    impl_->client->alter_database(std::string(name), thrift_db);
    return {};
  } catch (const NoSuchObjectException& e) {
    return UnknownDBError("alter_database", e.message);
  } catch (const InvalidOperationException& e) {
    return InvalidOperationError("alter_database", e.message);
  } catch (const MetaException& e) {
    return MetaError("alter_database", e.message);
  } catch (const apache::thrift::transport::TTransportException& e) {
    return TransportError("alter_database", e.what());

  } catch (const apache::thrift::TException& e) {
    return GenericThriftError("alter_database", e.what());
  }
}

// ---------------------------------------------------------------------------
// Table operations. Same pattern as the database wrappers above.

Result<std::vector<std::string>> HmsClient::GetAllTables(std::string_view db_name) {
  std::vector<std::string> names;
  try {
    impl_->client->get_all_tables(names, std::string(db_name));
    return names;
  } catch (const NoSuchObjectException& e) {
    return UnknownDBError("get_all_tables", e.message);
  } catch (const UnknownDBException& e) {
    return UnknownDBError("get_all_tables", e.message);
  } catch (const MetaException& e) {
    return MetaError("get_all_tables", e.message);
  } catch (const apache::thrift::transport::TTransportException& e) {
    return TransportError("get_all_tables", e.what());

  } catch (const apache::thrift::TException& e) {
    return GenericThriftError("get_all_tables", e.what());
  }
}

Result<HiveTable> HmsClient::GetTable(std::string_view db_name,
                                      std::string_view table_name) {
  GetTableRequest request;
  request.__set_dbName(std::string(db_name));
  request.__set_tblName(std::string(table_name));
  GetTableResult result;
  try {
    impl_->client->get_table_req(result, request);
    return FromThriftTable(result.table);
  } catch (const NoSuchObjectException& e) {
    return UnknownTableError("get_table", e.message);
  } catch (const UnknownTableException& e) {
    return UnknownTableError("get_table", e.message);
  } catch (const UnknownDBException& e) {
    return UnknownDBError("get_table", e.message);
  } catch (const MetaException& e) {
    return MetaError("get_table", e.message);
  } catch (const apache::thrift::transport::TTransportException& e) {
    return TransportError("get_table", e.what());

  } catch (const apache::thrift::TException& e) {
    return GenericThriftError("get_table", e.what());
  }
}

Status HmsClient::CreateTable(const HiveTable& table) {
  const Table thrift_table = ToThriftTable(table);
  try {
    impl_->client->create_table(thrift_table);
    return {};
  } catch (const AlreadyExistsException& e) {
    return AlreadyExistsError("create_table", e.message);
  } catch (const InvalidObjectException& e) {
    return InvalidObjectError("create_table", e.message);
  } catch (const NoSuchObjectException& e) {
    return UnknownDBError("create_table", e.message);
  } catch (const MetaException& e) {
    return MetaError("create_table", e.message);
  } catch (const apache::thrift::transport::TTransportException& e) {
    return TransportError("create_table", e.what());

  } catch (const apache::thrift::TException& e) {
    return GenericThriftError("create_table", e.what());
  }
}

Status HmsClient::DropTable(std::string_view db_name, std::string_view table_name,
                            bool delete_data) {
  try {
    impl_->client->drop_table(std::string(db_name), std::string(table_name), delete_data);
    return {};
  } catch (const NoSuchObjectException& e) {
    return UnknownTableError("drop_table", e.message);
  } catch (const InvalidOperationException& e) {
    return InvalidOperationError("drop_table", e.message);
  } catch (const MetaException& e) {
    return MetaError("drop_table", e.message);
  } catch (const apache::thrift::transport::TTransportException& e) {
    return TransportError("drop_table", e.what());

  } catch (const apache::thrift::TException& e) {
    return GenericThriftError("drop_table", e.what());
  }
}

Status HmsClient::AlterTable(std::string_view db_name, std::string_view table_name,
                             const HiveTable& new_table) {
  const Table thrift_table = ToThriftTable(new_table);
  try {
    impl_->client->alter_table(std::string(db_name), std::string(table_name),
                               thrift_table);
    return {};
  } catch (const NoSuchObjectException& e) {
    return UnknownTableError("alter_table", e.message);
  } catch (const InvalidObjectException& e) {
    return InvalidObjectError("alter_table", e.message);
  } catch (const InvalidOperationException& e) {
    return InvalidOperationError("alter_table", e.message);
  } catch (const MetaException& e) {
    return MetaError("alter_table", e.message);
  } catch (const apache::thrift::transport::TTransportException& e) {
    return TransportError("alter_table", e.what());

  } catch (const apache::thrift::TException& e) {
    return GenericThriftError("alter_table", e.what());
  }
}

// ---------------------------------------------------------------------------
// HMS locks. Used only when the catalog is configured with
// `hive.lock-enabled=true`. Failure to acquire the lock surfaces as
// kCommitFailed so iceberg::Transaction's retry loop can roll forward.

namespace {
// Poll `check_lock(lockid)` until ACQUIRED, a final-failure state, or the
// caller's acquire timeout. Returns the final LockState (which the caller
// then maps to either an HmsLockHandle or a CommitFailed error).
struct CheckLockOutcome {
  LockState::type state;
  std::string error_message;
  // Set when the polling loop bailed because the underlying Thrift
  // transport failed. LockExclusive uses this to surface a
  // `TransportError` (kServiceUnavailable) so HmsClientPool can drop the
  // broken connection and reconnect, matching the non-polling RPC paths.
  bool transport_failed = false;
};

CheckLockOutcome PollCheckLock(Apache::Hadoop::Hive::ThriftHiveMetastoreClient* client,
                               int64_t lockid, const HmsLockOptions& options) {
  using clock = std::chrono::steady_clock;
  const auto deadline =
      clock::now() + std::chrono::milliseconds(options.acquire_timeout_ms);
  // Use int64_t for the running wait so the `1.5x` backoff multiplication
  // cannot overflow even if a caller passes pathological check_max_wait_ms.
  std::int64_t wait_ms = std::max(1, options.check_min_wait_ms);
  const std::int64_t max_wait_ms =
      std::max<std::int64_t>(wait_ms, options.check_max_wait_ms);

  while (true) {
    if (clock::now() >= deadline) {
      return {.state = LockState::WAITING,
              .error_message = "acquire timeout elapsed before HMS acquired the lock"};
    }
    std::this_thread::sleep_for(std::chrono::milliseconds(wait_ms));

    LockResponse response;
    Apache::Hadoop::Hive::CheckLockRequest request;
    request.__set_lockid(lockid);
    try {
      client->check_lock(response, request);
    } catch (const NoSuchLockException& e) {
      return {.state = LockState::ABORT,
              .error_message =
                  std::format("HMS check_lock: lock {} vanished: {}", lockid, e.message)};
    } catch (const TxnAbortedException& e) {
      return {.state = LockState::ABORT,
              .error_message = std::format("HMS check_lock: txn aborted: {}", e.message)};
    } catch (const TxnOpenException& e) {
      return {
          .state = LockState::ABORT,
          .error_message = std::format("HMS check_lock: txn open error: {}", e.message)};
    } catch (const MetaException& e) {
      return {
          .state = LockState::ABORT,
          .error_message = std::format("HMS check_lock MetaException: {}", e.message)};
    } catch (const apache::thrift::transport::TTransportException& e) {
      return {
          .state = LockState::ABORT,
          .error_message = std::format("HMS check_lock transport error: {}", e.what()),
          .transport_failed = true};
    } catch (const apache::thrift::TException& e) {
      return {.state = LockState::ABORT,
              .error_message = std::format("HMS check_lock thrift error: {}", e.what())};
    }
    if (response.state == LockState::ACQUIRED) {
      return {.state = response.state, .error_message = ""};
    }
    if (response.state != LockState::WAITING) {
      return {.state = response.state, .error_message = response.errorMessage};
    }
    // Exponential backoff with cap, matching Java's `Tasks.exponentialBackoff(1.5)`.
    wait_ms = std::min(max_wait_ms, (wait_ms * 3 + 1) / 2);
  }
}
}  // namespace

Result<HmsClient::HmsLockHandle> HmsClient::LockExclusive(std::string_view db_name,
                                                          std::string_view table_name,
                                                          const HmsLockOptions& options) {
  LockComponent component;
  component.__set_type(LockType::EXCLUSIVE);
  component.__set_level(LockLevel::TABLE);
  component.__set_dbname(std::string(db_name));
  component.__set_tablename(std::string(table_name));
  component.__set_isTransactional(false);
  component.__set_isDynamicPartitionWrite(false);

  LockRequest request;
  request.__set_component({component});
  // No transaction context; iceberg_hive uses HMS locks purely as an
  // advisory mutex around metadata_location CAS.
  request.__set_txnid(0);

  LockResponse response;
  try {
    impl_->client->lock(response, request);
  } catch (const TxnAbortedException& e) {
    return CommitFailed("HMS aborted lock txn on {}.{}: {}", db_name, table_name,
                        e.message);
  } catch (const MetaException& e) {
    return MetaError("lock", e.message);
  } catch (const apache::thrift::transport::TTransportException& e) {
    return TransportError("lock", e.what());

  } catch (const apache::thrift::TException& e) {
    return GenericThriftError("lock", e.what());
  }

  if (response.state == LockState::ACQUIRED) {
    return HmsLockHandle{.lock_id = response.lockid};
  }
  if (response.state == LockState::WAITING) {
    // Poll until ACQUIRED, a final failure, or timeout. Java's Tasks
    // helper does this same exponential-backoff loop; do not reuse the
    // initial CommitFailed path so high-contention deployments actually
    // get a chance to acquire the lock.
    auto outcome = PollCheckLock(impl_->client.get(), response.lockid, options);
    if (outcome.state == LockState::ACQUIRED) {
      return HmsLockHandle{.lock_id = response.lockid};
    }
    if (outcome.transport_failed) {
      // Transport is dead -- Unlock on the same client would also fail
      // and merely leak the queued lock at the HMS side. Surface
      // kServiceUnavailable so HmsClientPool reconnects and the caller's
      // next attempt can clean up via a fresh client.
      return TransportError("check_lock", outcome.error_message);
    }
    // Release the queued handle before surfacing failure so we don't leak
    // a slot in HMS's wait list for the full server-side lease.
    (void)Unlock(HmsLockHandle{.lock_id = response.lockid});
    return CommitFailed(
        "HMS denied EXCLUSIVE lock on {}.{} after polling (state={}, error={}); "
        "retry the transaction.",
        db_name, table_name, static_cast<int>(outcome.state), outcome.error_message);
  }

  // Initial NOT_ACQUIRED / ABORT -- HMS already has a final answer; no
  // point polling. Free the queued handle and bail.
  (void)Unlock(HmsLockHandle{.lock_id = response.lockid});
  return CommitFailed(
      "HMS denied EXCLUSIVE lock on {}.{} (state={}, error={}); retry the "
      "transaction.",
      db_name, table_name, static_cast<int>(response.state), response.errorMessage);
}

Status HmsClient::Unlock(HmsLockHandle handle) {
  if (!handle.acquired()) {
    return {};
  }
  UnlockRequest request;
  request.__set_lockid(handle.lock_id);
  try {
    impl_->client->unlock(request);
    return {};
  } catch (const NoSuchLockException& e) {
    return NotFound("HMS reports lock {} no longer exists: {}", handle.lock_id,
                    e.message);
  } catch (const TxnOpenException& e) {
    return InvalidOperationError("unlock", e.message);
  } catch (const MetaException& e) {
    return MetaError("unlock", e.message);
  } catch (const apache::thrift::transport::TTransportException& e) {
    return TransportError("unlock", e.what());

  } catch (const apache::thrift::TException& e) {
    return GenericThriftError("unlock", e.what());
  }
}

Status HmsClient::Heartbeat(int64_t lock_id) {
  HeartbeatRequest request;
  request.__set_lockid(lock_id);
  request.__set_txnid(0);
  try {
    impl_->client->heartbeat(request);
    return {};
  } catch (const NoSuchLockException& e) {
    return NotFound("HMS reports lock {} no longer exists: {}", lock_id, e.message);
  } catch (const TxnAbortedException& e) {
    return CommitFailed("HMS heartbeat: txn aborted: {}", e.message);
  } catch (const MetaException& e) {
    return MetaError("heartbeat", e.message);
  } catch (const apache::thrift::transport::TTransportException& e) {
    return TransportError("heartbeat", e.what());
  } catch (const apache::thrift::TException& e) {
    return GenericThriftError("heartbeat", e.what());
  }
}

// ---------------------------------------------------------------------------
// HmsLockHeartbeat: dedicated background thread + dedicated HMS client.
// Java's MetastoreLock uses a scheduled executor; we use one std::thread per
// held lock because commits are infrequent and the simpler model avoids a
// shared scheduler. The thread owns its own HmsClient connection so it cannot
// race with the commit path that owns the pooled client.

class HmsLockHeartbeat::Impl {
 public:
  std::unique_ptr<HmsClient> client;
  int64_t lock_id = -1;
  int32_t interval_ms = 0;
  std::mutex mu;
  std::condition_variable cv;
  bool stopping = false;
  std::thread worker;

  void Run() {
    // Fire at half the configured interval so HMS sees a heartbeat well
    // before its txn.timeout, mirroring MetastoreLock's `interval / 2`.
    const auto sleep_for = std::chrono::milliseconds(std::max(1, interval_ms / 2));
    std::unique_lock<std::mutex> lock(mu);
    while (!stopping) {
      if (cv.wait_for(lock, sleep_for, [&] { return stopping; })) {
        return;
      }
      // Release the mutex during the RPC so Stop() can preempt a slow
      // heartbeat without waiting for the RPC to finish.
      lock.unlock();
      (void)client->Heartbeat(lock_id);
      lock.lock();
    }
  }
};

HmsLockHeartbeat::HmsLockHeartbeat(std::unique_ptr<Impl> impl) : impl_(std::move(impl)) {}

HmsLockHeartbeat::~HmsLockHeartbeat() { Stop(); }

Result<std::unique_ptr<HmsLockHeartbeat>> HmsLockHeartbeat::Start(
    const HiveCatalogProperties& config, int64_t lock_id, int32_t interval_ms) {
  ICEBERG_ASSIGN_OR_RAISE(auto client, HmsClient::Connect(config));
  auto impl = std::make_unique<Impl>();
  impl->client = std::move(client);
  impl->lock_id = lock_id;
  impl->interval_ms = interval_ms;
  // Transfer ownership of `impl` into the heartbeater BEFORE starting
  // the worker thread, so the lambda only captures the pointer that
  // already lives inside the returned object. This makes the lifetime
  // contract -- `HmsLockHeartbeat::~HmsLockHeartbeat` joins the thread
  // -- structurally obvious instead of relying on RVO ordering.
  std::unique_ptr<HmsLockHeartbeat> heartbeat(new HmsLockHeartbeat(std::move(impl)));
  Impl* impl_ptr = heartbeat->impl_.get();
  impl_ptr->worker = std::thread([impl_ptr] { impl_ptr->Run(); });
  return heartbeat;
}

void HmsLockHeartbeat::Stop() {
  if (!impl_) {
    return;
  }
  {
    std::lock_guard<std::mutex> lock(impl_->mu);
    if (impl_->stopping) {
      return;
    }
    impl_->stopping = true;
  }
  impl_->cv.notify_all();
  if (impl_->worker.joinable()) {
    impl_->worker.join();
  }
}

}  // namespace iceberg::hive
